# Generated by Django 2.2.6 on 2019-12-06 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('pharmacistId', models.AutoField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=33)),
                ('drugLicence', models.CharField(max_length=33)),
                ('phoneNumber', models.CharField(max_length=18)),
                ('storeAddress', models.CharField(max_length=33)),
                ('password', models.CharField(max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='SoldMedicineWithoutPrescription',
            fields=[
                ('soldMedicineWithoutPrescriptionId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(max_length=50)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Medicine')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacist.Pharmacist')),
            ],
        ),
        migrations.CreateModel(
            name='SoldMedicine',
            fields=[
                ('soldMedicineId', models.AutoField(primary_key=True, serialize=False)),
                ('medicineQuantity', models.CharField(max_length=20)),
                ('soldDate', models.DateField(default=django.utils.timezone.now)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacist.Pharmacist')),
                ('prescribedMedicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.PrescribedMedicine')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(max_length=20)),
                ('confirmationState', models.CharField(max_length=20)),
                ('deliveryDate', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Company')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Medicine')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacist.Pharmacist')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('medicineStockId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(max_length=50)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Medicine')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacist.Pharmacist')),
            ],
        ),
    ]
