# Generated by Django 2.2.6 on 2019-12-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='company',
        ),
    ]
