# Generated by Django 2.2.6 on 2019-12-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
        ('Pharmacist', '0002_remove_order_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Company.Company'),
            preserve_default=False,
        ),
    ]
