# Generated by Django 2.2.6 on 2019-12-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorId', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[("MA'S", "MA'S"), ('CTS', 'CTS')], max_length=15)),
                ('type', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
